# Generated by Django 4.2.3 on 2023-07-29 14:05

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("dogs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dogpage",
            name="album",
        ),
        migrations.RemoveField(
            model_name="dogpage",
            name="image",
        ),
        migrations.AddField(
            model_name="dogpage",
            name="facebook_url",
            field=models.URLField(
                blank=True,
                help_text="Link to Facebook album page for this dog",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="DogPageGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("caption", models.CharField(blank=True, max_length=250)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="dogs.dogpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
