# Generated by Django 4.2.3 on 2023-07-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("dogs", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DogStatusIndexPage",
            new_name="DogStatusPage",
        ),
    ]
