# Generated by Django 4.2.3 on 2023-07-21 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("dogs", "0002_rename_dogstatusindexpage_dogstatuspage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DogsIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AddField(
            model_name="dogstatuspage",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="A one-line description of this status",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
