# Generated by Django 4.2.4 on 2023-09-29 11:06

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0002_remove_dogpage_album_remove_dogpage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dogsindexpage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
