# Generated by Django 4.2.3 on 2023-09-30 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("dogs", "0003_dogsindexpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="dogsindexpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Header image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="dogstatuspage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Header image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
