# Generated by Django 4.2.3 on 2023-10-06 15:46

from django.db import migrations, models
import django.utils.timezone
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0004_dogsindexpage_image_dogstatuspage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookAlbums",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("albums", models.JSONField()),
                (
                    "date_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="dogpage",
            name="facebook_url",
        ),
        migrations.AddField(
            model_name="dogpage",
            name="facebook_album_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dogpage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Description to use instead of Facebook album description. Leave blank to use descripton from album page.",
            ),
        ),
    ]
