# Generated by Django 4.2.3 on 2023-07-21 17:01

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0004_dogindexpagestatuses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dogindexpagestatuses",
            name="status",
        ),
        migrations.AddField(
            model_name="dogindexpagestatuses",
            name="status_page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="dogs.dogstatuspage",
            ),
        ),
        migrations.AlterField(
            model_name="dogindexpagestatuses",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dog_status_pages",
                to="dogs.dogsindexpage",
            ),
        ),
    ]
