# Generated by Django 4.2.3 on 2023-10-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0005_facebookalbums_remove_dogpage_facebook_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dogpage",
            name="cover_image_index",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
