# Generated by Django 4.2.3 on 2023-07-21 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0005_remove_dogindexpagestatuses_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dogindexpagestatuses",
            name="status_page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="dogs.dogstatuspage",
                verbose_name="Dog status category",
            ),
        ),
    ]
