# Generated by Django 4.2.3 on 2023-10-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0006_dogpage_cover_image_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="dogpage",
            name="caption",
            field=models.CharField(
                blank=True,
                help_text="Short caption to be used on status page. Defaults to first sentence of facebook album description.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="DogPageGalleryImage",
        ),
    ]
