# Generated by Django 4.2.3 on 2023-07-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0006_alter_dogindexpagestatuses_status_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dogstatuspage",
            name="status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="Status",
        ),
    ]
