# Generated by Django 4.2.3 on 2023-07-22 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0007_alter_dogstatuspage_status_delete_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dogstatuspage",
            name="status",
        ),
    ]
