# Generated by Django 4.2.3 on 2023-10-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0007_dogpage_caption_delete_dogpagegalleryimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookalbums",
            name="rate_limited_at",
            field=models.DateTimeField(null=True),
        ),
    ]
