# Generated by Django 4.2.3 on 2023-10-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0008_facebookalbums_rate_limited_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="dogpage",
            name="custom_album_data",
            field=models.JSONField(
                blank=True,
                help_text="Custom album data to use if FB album can't be retrieved.Format: {'link': '<link to fb album>', 'images': [{'image_url': <url>}]}",
                null=True,
            ),
        ),
    ]
