# Generated by Django 4.2.3 on 2023-10-23 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0009_dogpage_custom_album_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dogpage",
            name="custom_album_data",
        ),
    ]
