# Generated by Django 4.2.3 on 2023-10-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0011_dogpagegalleryimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="dogpagegalleryimage",
            name="fb_image_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
