# Generated by Django 4.2.3 on 2023-11-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0012_dogpagegalleryimage_fb_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookalbums',
            name='previous_albums',
            field=models.JSONField(default=dict),
        ),
    ]
