# Generated by Django 5.0.1 on 2024-03-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0013_facebookalbums_previous_albums'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogpagegalleryimage',
            options={'ordering': ('-fb_image_id',)},
        ),
    ]
