# Generated by Django 4.2.3 on 2023-07-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GenericSettings",
            new_name="SocialSettings",
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="title_suffix",
            field=models.CharField(
                default="Podencos In Need Scotland",
                help_text="The suffix for the title meta tag e.g. ' | Podencos In Need Scotland'",
                max_length=255,
                verbose_name="Title suffix",
            ),
        ),
    ]
