# Generated by Django 4.2.3 on 2023-07-21 15:02

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail.fields
import wagtail.models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.RichTextField(default="text"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="featured_section_1",
            field=models.ForeignKey(
                blank=True,
                help_text="First featured section for the homepage. Will display up to three child items.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Featured section 1",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="featured_section_1_title",
            field=models.CharField(
                blank=True,
                help_text="Title to display above the promo copy",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="featured_section_2",
            field=models.ForeignKey(
                blank=True,
                help_text="Second featured section for the homepage. Will display up to three child items.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Featured section 2",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="featured_section_2_title",
            field=models.CharField(
                blank=True,
                help_text="Title to display above the promo copy",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="featured_section_3",
            field=models.ForeignKey(
                blank=True,
                help_text="Third featured section for the homepage. Will display up to six child items.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Featured section 3",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="featured_section_3_title",
            field=models.CharField(
                blank=True,
                help_text="Title to display above the promo copy",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta",
            field=models.CharField(
                default="cta",
                help_text="Text to display on Call to Action",
                max_length=255,
                verbose_name="Hero CTA",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose a page to link to for the Call to Action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Hero CTA link",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_text",
            field=models.CharField(
                default="hero",
                help_text="Write an introduction for the home page",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Homepage image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="promo_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Promo image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="promo_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Write some promotional copy",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="promo_title",
            field=models.CharField(
                blank=True,
                help_text="Title to display above the promo copy",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="FooterText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translation_key",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "live",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="live"
                    ),
                ),
                (
                    "has_unpublished_changes",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="has unpublished changes",
                    ),
                ),
                (
                    "first_published_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="first published at",
                    ),
                ),
                (
                    "last_published_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="last published at"
                    ),
                ),
                (
                    "go_live_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="go live date/time"
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expiry date/time"
                    ),
                ),
                (
                    "expired",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="expired"
                    ),
                ),
                ("body", wagtail.fields.RichTextField()),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "live_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="live revision",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Footer Text",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
            bases=(wagtail.models.PreviewableMixin, models.Model),
        ),
    ]
