# Generated by Django 4.2.3 on 2023-07-21 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("home", "0003_homepage_body_homepage_featured_section_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_footer",
            field=models.CharField(
                blank=True,
                help_text="Text to display on the Footer link button",
                max_length=255,
                null=True,
                verbose_name="Hero Footer",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_footer_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose a page to link to for the Footer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Hero CTA link",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_footer_text",
            field=models.CharField(
                blank=True,
                help_text="Text to display on the home page footer image",
                max_length=255,
                null=True,
            ),
        ),
    ]
