# Generated by Django 4.2.3 on 2023-08-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_orderformpage_product_cost_productvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariant",
            name="slug",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This field will be autopoulated",
                max_length=60,
            ),
        ),
    ]
