# Generated by Django 4.2.3 on 2023-08-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_productvariant_name_productvariant_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="quantity_choices",
            field=models.CharField(
                default="0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20",
                help_text="Comma separated list of quantity choices for the drop down menu",
                max_length=255,
            ),
        ),
    ]
