# Generated by Django 4.2.3 on 2023-08-31 12:06

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_productvariant_quantity_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderformpage",
            name="form_footer_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
