# Generated by Django 4.2.4 on 2023-09-29 11:39

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_orderformpage_form_footer_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="featured_section_body",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Optional description for the featured section",
                max_length=1000,
                null=True,
            ),
        ),
    ]
