# Generated by Django 4.2.3 on 2023-10-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_orderformpage_inline_image_standardpage_inline_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderformpage",
            name="total_available",
            field=models.PositiveIntegerField(
                blank=True, help_text="Max total number available (optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="item_count",
            field=models.PositiveIntegerField(
                default=1,
                help_text="The number of individual items represented by this variant, used for stock checking. i.e. A pack of 5 = 5 items",
            ),
        ),
    ]
