# Generated by Django 4.2.3 on 2023-10-22 09:18

from django.db import migrations


def create_form_submissions(apps, schema_editor):
    OrderFormSubmission = apps.get_model("home", "OrderFormSubmission")
    FormSubmission = apps.get_model("wagtailforms", "FormSubmission")

    submissions = FormSubmission.objects.all()
    for submission in submissions:
        if "order-form" in submission.page.slug:
            OrderFormSubmission.objects.create(
                page=submission.page,
                form_data=submission.form_data,
                submit_time=submission.submit_time,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_orderformsubmission"),
        ("wagtailforms", "0005_alter_formsubmission_form_data"),
    ]

    operations = [
        migrations.RunPython(create_form_submissions, migrations.RunPython.noop)
    ]
