# Generated by Django 4.2.3 on 2023-11-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_create_order_form_submissions_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='button_display',
            field=models.CharField(choices=[('top', 'Top of page'), ('bottom', 'Bottom of page'), ('both', 'Top and bottom of page')], default='top'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='button_styling',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='button_text',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='button_url',
            field=models.URLField(blank=True),
        ),
    ]
