# Generated by Django 5.0.1 on 2024-01-26 14:49

from decimal import Decimal
from django.db import migrations


def add_cost(apps, schema_editor):
    OrderFormSubmission = apps.get_model("home", "OrderFormSubmission")
    ProductVariant = apps.get_model("home", "ProductVariant")

    shipping_costs = {
        "Tea Towel Order Form": Decimal("3.95"),
        "PINS 2024 Calendar Order Form": Decimal("3.50"),
    }

    def get_item(v):
        if isinstance(v, list):
            return int(v[0])
        return int(v)     

    for submission in OrderFormSubmission.objects.filter(cost__isnull=True):
        product_variants = ProductVariant.objects.filter(page=submission.page)
        product_variant_slugs = product_variants.values_list("slug", flat=True)
        quantities = {
            k: get_item(v) for k, v in submission.form_data.items() if k in product_variant_slugs
        }

        total = 0
        variant_quantities = {}
        for key, quantity in quantities.items():
            variant = product_variants.get(slug=key)
            variant_quantities[key] = (variant, quantity)
            total += (variant.cost * quantity)
        if total > 0:
            total += shipping_costs.get(submission.page.title, 0)

        submission.cost = total
        submission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_orderformsubmission_cost'),
    ]

    operations = [
        migrations.RunPython(add_cost, reverse_code=migrations.RunPython.noop),
    ]
