# Generated by Django 5.0.1 on 2024-01-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20240126_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordervoucher',
            options={},
        ),
        migrations.AddField(
            model_name='orderformsubmission',
            name='date_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordervoucher',
            name='one_time_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='ordervoucher',
            unique_together={('order_form_page', 'code')},
        ),
    ]
