# Generated by Django 5.0.1 on 2024-01-30 15:02

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_ordervoucher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShippingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_form_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_costs', to='home.orderformpage')),
            ],
            options={
                'ordering': ('max_quantity',),
            },
        ),
    ]
