# Generated by Django 5.0.1 on 2024-01-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_ordershippingcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderformpage',
            name='shipping_cost',
        ),
        migrations.AlterUniqueTogether(
            name='ordershippingcost',
            unique_together={('order_form_page', 'max_quantity')},
        ),
    ]
