# Generated by Django 5.0.1 on 2024-01-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_orderformpage_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershippingcost',
            name='max_quantity',
            field=models.PositiveIntegerField(default=999999999),
        ),
    ]
