# Generated by Django 5.0.1 on 2024-02-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_ordershippingcost_max_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='group_name',
            field=models.CharField(blank=True, help_text='Optional group for this variant. Use to group variants with multiple options, e.g. sizes', max_length=100),
        ),
    ]
