# Generated by Django 5.0.1 on 2024-02-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_productvariant_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderformpage',
            name='show_summary',
            field=models.BooleanField(default=False, help_text='Show a summary of order options before form.'),
        ),
    ]
