# Generated by Django 5.0.1 on 2024-02-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_pdfformpage_pdfformfield_pdfformsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfformsubmission',
            name='token',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='pdfformsubmission',
            name='token_expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
