# Generated by Django 5.0.1 on 2024-02-08 11:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_pdfformsubmission_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfformfield',
            name='after_info_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='pdfformfield',
            name='before_info_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
