# Generated by Django 5.0.1 on 2024-02-12 18:31

import django.core.serializers.json
import encrypted_json_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_pdfformsubmission_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfformfield',
            name='required_for_draft',
            field=models.BooleanField(default=False, help_text='Required in order to save as draft'),
        ),
        migrations.AlterField(
            model_name='orderformsubmission',
            name='form_data',
            field=encrypted_json_fields.fields.EncryptedJSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
