# Generated by Django 5.1 on 2024-10-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0034_orderformpage_uploaded_image_collection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="default_value",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="group_total_available",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="variant_total_available",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
