# Generated by Django 4.2.3 on 2024-01-15 11:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeBookSubmission',
            fields=[
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Your name')),
                ('email', models.EmailField(help_text='Your email; we will send a copy of your submission to this address', max_length=254)),
                ('page_type', models.CharField(choices=[('single', 'Single recipe page'), ('double', 'Double recipe page'), ('single_with_facing', 'Single page recipe with full page facing photo'), ('photo', 'Photo page only')])),
                ('title', models.CharField(blank=True, help_text='Title of recipe')),
                ('preparation_time', models.CharField(blank=True, help_text='Preparation time (please include units)')),
                ('cook_time', models.CharField(blank=True, help_text='Cook time (please include units)')),
                ('servings', models.CharField(blank=True, help_text='How many servings does the recipe make? e.g. serves 4, makes 16')),
                ('ingredients', models.TextField(blank=True, help_text='List ingredients as they should appear in the recipe (include subheadings if you want)')),
                ('method', models.TextField(blank=True, help_text='Method; please separate paragraphs with a blank line')),
                ('submitted_by', models.CharField(blank=True, help_text="Name(s) for the 'Submitted by' section in the recipe. This can be your full name, your first name, your dog's name - however you want it to appear e.g. 'Becky & Nala'. This will appear next to your profile image.")),
                ('profile_caption', models.TextField(blank=True, help_text='Optional caption to go with your profile image. E.g. Say something about the recipe, about why you chose it, or about your dog(s), when they were adopted etc.')),
                ('photo_caption', models.CharField(blank=True, null=True)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid', models.BooleanField(default=False)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('date_complete', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('profile_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
    ]
