# Generated by Django 5.0.1 on 2024-01-20 18:00

import django.core.validators
import fundraising.models
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipebooksubmission',
            name='date_complete',
        ),
        migrations.AddField(
            model_name='recipebooksubmission',
            name='code',
            field=models.PositiveIntegerField(default=4833),
        ),
        migrations.AddField(
            model_name='recipebooksubmission',
            name='photo_title',
            field=models.CharField(blank=True, help_text="Title for photo (e.g. dog's name)", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipebooksubmission',
            name='processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipebooksubmission',
            name='cook_time',
            field=models.CharField(blank=True, help_text='Cook time (please include units)', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipebooksubmission',
            name='ingredients',
            field=models.TextField(blank=True, help_text='List ingredients as they should appear in the recipe (include subheadings if you want)', max_length=500),
        ),
        migrations.AlterField(
            model_name='recipebooksubmission',
            name='method',
            field=models.TextField(blank=True, help_text='Recipe instructions'),
        ),
        migrations.AlterField(
            model_name='recipebooksubmission',
            name='photo',
            field=models.ImageField(blank=True, help_text='In order to print at good quality (300dpi), we photos with min width 1500px, min height 2100px. To print a full borderless page, photos need to be min width 2490px, min height 3510px. ', null=True, upload_to=fundraising.models.image_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg']), fundraising.models.validate_photo]),
        ),
        migrations.AlterField(
            model_name='recipebooksubmission',
            name='photo_caption',
            field=models.CharField(blank=True, help_text='Optional: A short caption to print under photo title', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipebooksubmission',
            name='preparation_time',
            field=models.CharField(blank=True, help_text='Preparation time (please include units)', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipebooksubmission',
            name='profile_caption',
            field=models.TextField(blank=True, help_text='Optional caption to go with your profile image. E.g. Say something about the recipe, about why you chose it, or about your dog(s), when they were adopted etc.', max_length=300),
        ),
        migrations.AlterField(
            model_name='recipebooksubmission',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='In order to print at good quality, we require photos at min 300dpi, width 710px, height 520px.', null=True, upload_to=fundraising.models.image_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg']), fundraising.models.validate_profile_image]),
        ),
        migrations.AlterField(
            model_name='recipebooksubmission',
            name='reference',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=22, max_length=22, prefix='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipebooksubmission',
            name='servings',
            field=models.CharField(blank=True, help_text='How many servings does the recipe make? e.g. serves 4, makes 16', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipebooksubmission',
            name='submitted_by',
            field=models.CharField(blank=True, help_text="Name(s) for the 'Submitted by' section in the recipe. This can be your full name, your first name, your dog's name - however you want it to appear e.g. 'Becky & Nala'. This will appear next to your profile image.", max_length=100),
        ),
        migrations.AlterField(
            model_name='recipebooksubmission',
            name='title',
            field=models.CharField(blank=True, help_text='Title of recipe. Maximum 100 characters.', max_length=100),
        ),
    ]
