# Generated by Django 5.0.1 on 2024-01-19 16:01

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0002_remove_recipebooksubmission_date_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipebooksubmission',
            name='reference',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=22, max_length=22, prefix='', primary_key=True, serialize=False),
        ),
    ]
