# Generated by Django 5.0.1 on 2024-01-21 10:20

import django.core.validators
import fundraising.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0002_remove_recipebooksubmission_date_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipebooksubmission',
            name='code',
            field=models.PositiveIntegerField(default=5673),
        ),
        migrations.AlterField(
            model_name='recipebooksubmission',
            name='photo',
            field=models.ImageField(blank=True, help_text='Please upload the highest quality photo you can (up to 10Mb). To print a full borderless page at 300dpi, photos need to be min width 2490px, min height 3510px. You can upload a photo smaller than this (min width 1500px, min height 2100px) but they may need to be printed smaller than full page.', null=True, upload_to=fundraising.models.image_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg']), fundraising.models.validate_photo]),
        ),
    ]
