# Generated by Django 5.0.1 on 2024-01-18 13:14

import fundraising.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0002_alter_recipebooksubmission_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipebooksubmission',
            name='date_complete',
        ),
        migrations.AddField(
            model_name='recipebooksubmission',
            name='processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipebooksubmission',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=fundraising.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='recipebooksubmission',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=fundraising.models.image_upload_path),
        ),
    ]
