# Generated by Django 5.0.1 on 2024-01-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0003_alter_recipebooksubmission_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipebooksubmission',
            name='category',
            field=models.CharField(blank=True, choices=[('dog', 'Dog recipes'), ('human', 'Human recipes')]),
        ),
        migrations.AlterField(
            model_name='recipebooksubmission',
            name='code',
            field=models.PositiveIntegerField(default=2523),
        ),
    ]
