# Generated by Django 5.0.1 on 2024-02-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0005_alter_recipebooksubmission_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipebooksubmission',
            options={'ordering': ('-date_submitted',)},
        ),
    ]
