# Generated by Django 5.1 on 2024-09-14 15:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fundraising",
            "0007_auction_auctioncategory_auctionitem_auctionitemphoto_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auctioncategory",
            options={"verbose_name_plural": "Auction categories"},
        ),
        migrations.AddField(
            model_name="bid",
            name="address_line_1",
            field=models.CharField(
                blank=True, null=True, verbose_name="Street address (1)"
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="address_line_2",
            field=models.CharField(
                blank=True, null=True, verbose_name="Street address (2)"
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="address_line_3",
            field=models.CharField(
                blank=True, null=True, verbose_name="Street address (3)"
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="county",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bid",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bid",
            name="placed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="bid",
            name="postcode",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bid",
            name="town_city",
            field=models.CharField(blank=True, null=True, verbose_name="Town/City"),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="starting_bid",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="bid",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="bid",
            name="notify",
            field=models.BooleanField(
                default=True, help_text="Notify me when someone places a higher bid"
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
