# Generated by Django 5.1 on 2024-09-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraising", "0010_auctionspage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auction",
            options={"ordering": ("close_at",)},
        ),
        migrations.AddField(
            model_name="bid",
            name="address_lines",
            field=models.TextField(blank=True, null=True),
        ),
    ]
