# Generated by Django 5.1 on 2024-09-21 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraising", "0011_alter_auction_options_bid_address_lines"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="address_lines",
        ),
        migrations.CreateModel(
            name="UserShippingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("address_line_1", models.CharField(verbose_name="Street address (1)")),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, null=True, verbose_name="Street address (2)"
                    ),
                ),
                (
                    "address_line_3",
                    models.CharField(
                        blank=True, null=True, verbose_name="Street address (3)"
                    ),
                ),
                ("town_city", models.CharField(verbose_name="Town/City")),
                ("county", models.CharField()),
                ("postcode", models.CharField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
