# Generated by Django 5.1 on 2024-09-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraising", "0012_remove_bid_address_lines_usershippingaddress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auction",
            options={"ordering": ("-close_at",)},
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="postage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
