# Generated by Django 5.1 on 2024-10-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraising", "0014_bid_donor_notified_bid_winner_notified_bid_withdrawn"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionitem",
            name="show_donor",
            field=models.BooleanField(
                default=True, help_text="Display donor's name on item page"
            ),
        ),
    ]
