# Generated by Django 5.1 on 2024-11-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraising", "0015_auctionitem_show_donor"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionitem",
            name="unsold_notification_sent",
            field=models.BooleanField(default=False),
        ),
    ]
